# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  macos: circleci/macos@2.3.2

references:
  defaults: &defaults
    working_directory: /Users/distiller/project
    macos:
        xcode: "13.4.1"

  derived_data_path: &derived_data_path build

  persist_data: &persist_workspace
          persist_to_workspace:
              root: .
              paths:
                - .

  attach_data: &attach_workspace
        attach_workspace:
            at: .      

  pre_run_iphone: &pre_run_iphone
      macos/preboot-simulator:
          version: "15.5"
          platform: "iOS"
          device: "iPhone 13"            

jobs:
  fetch:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-cache-{{ checksum "Gemfile.lock" }}
            - bundle-cache
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - bundle-cache
      - *persist_workspace
  
  build-for-test:
    <<: *defaults
    environment:
      SCAN_DEVICE: iPhone 13
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - *attach_workspace
      - run:
          name: Build for testing
          command: bundle exec fastlane build_for_ui_test
          environment:
              SCAN_DEVICE: iPhone 13
              SCAN_SCHEME: AmazingSeriesUITests
      - persist_to_workspace:
          root: .
          paths:
              - *derived_data_path
  
  ui-tests-1:
    <<: *defaults
    steps:
        - *attach_workspace
        - *pre_run_iphone
        - run:
            name: Run ui tests
            command: bundle exec fastlane ui_test_1
            environment:
                SCAN_DEVICE: iPhone 13
                SCAN_SCHEME: AmazingSeriesUITests
        - run:
            command: mv fastlane/test_output/report.junit fastlane/test_output/ui_tests_report.xml
            when: always

  ui-tests-2:
    <<: *defaults
    steps:
        - *attach_workspace
        - *pre_run_iphone
        - run:
            name: Run ui tests
            command: bundle exec fastlane ui_test_2
            environment:
                SCAN_DEVICE: iPhone 13
                SCAN_SCHEME: AmazingSeriesUITests
        - run:
            command: mv fastlane/test_output/report.junit fastlane/test_output/ui_tests_report.xml
            when: always
  ui-tests-3:
    <<: *defaults
    steps:
        - *attach_workspace
        - *pre_run_iphone
        - run:
            name: Run ui tests
            command: bundle exec fastlane ui_test_3
            environment:
                SCAN_DEVICE: iPhone 13
                SCAN_SCHEME: AmazingSeriesUITests
        - run:
            command: mv fastlane/test_output/report.junit fastlane/test_output/ui_tests_report.xml
            when: always

  ui-tests-4:
    <<: *defaults
    steps:
        - *attach_workspace
        - *pre_run_iphone
        - run:
            name: Run ui tests
            command: bundle exec fastlane ui_test_4
            environment:
                SCAN_DEVICE: iPhone 13
                SCAN_SCHEME: AmazingSeriesUITests
        - run:
            command: mv fastlane/test_output/report.junit fastlane/test_output/ui_tests_report.xml
            when: always

workflows:
  version: 2
  build-and-test:
    jobs:
      - fetch
      - build-for-test:
          name: amazingseries_uitests_scheme_build
          requires:
              - fetch
      - ui-tests-1:
          requires:
            - amazingseries_uitests_scheme_build
      - ui-tests-2:
          requires:
            - amazingseries_uitests_scheme_build
      - ui-tests-3:
          requires:
            - amazingseries_uitests_scheme_build