default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  lane :tests do
  run_tests(
      workspace: "AmazingSeries.xcworkspace",
      devices: ["iPhone 13"],
      scheme: "AmazingSeriesUITests",
      skip_detect_devices: true,
      skip_build: true,
      parallel_testing: true,
      concurrent_workers: 4
   )
  end
end
